- client: !!python/object/new:p2psimpy.config.PeerType
  - PeerConfig:
      bandwidth_dl:
        Dist:
          name: norm
          params: (6553600.0, 1310720.0)
      bandwidth_ul:
        Dist:
          name: norm
          params: (6553600.0, 1310720.0)
      location:
        Dist:
          name: sample
          params: '[''Ohio'', ''Ireland'', ''Tokyo'']'
  - BaseConnectionManager: null
    MessageProducer:
      MyMessageProducerConfig:
        init_ttl: 5
  peer: !!python/object/new:p2psimpy.config.PeerType
  - PeerConfig:
      bandwidth_dl:
        Dist:
          name: norm
          params: (6553600.0, 1310720.0)
      bandwidth_ul:
        Dist:
          name: norm
          params: (6553600.0, 1310720.0)
      location:
        Dist:
          name: sample
          params: '[''Ohio'', ''Ireland'', ''Tokyo'']'
  - BaseConnectionManager: null
    GossipService:
      MyGossipConfig:
        exclude_types: !!set
          bootstrap: null
          client: null
- BaseConnectionManager: null
  GossipService: null
  MessageProducer: null
